// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('web_apiKey'),
    appId: String.fromEnvironment('web_appId'),
    messagingSenderId: String.fromEnvironment('web_messagingSenderId'),
    projectId: String.fromEnvironment('web_projectId'),
    authDomain: String.fromEnvironment('web_authDomain'),
    storageBucket: String.fromEnvironment('web_storageBucket'),
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('android_apiKey'),
    appId: String.fromEnvironment('android_appId'),
    messagingSenderId: String.fromEnvironment('android_messagingSenderId'),
    projectId: String.fromEnvironment('android_projectId'),
    storageBucket: String.fromEnvironment('android_storageBucket'),
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('ios_apiKey'),
    appId: String.fromEnvironment('ios_appId'),
    messagingSenderId: String.fromEnvironment('ios_messagingSenderId'),
    projectId: String.fromEnvironment('ios_projectId'),
    storageBucket: String.fromEnvironment('ios_storageBucket'),
    iosBundleId: String.fromEnvironment('ios_iosBundleId'),
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('macos_apiKey'),
    appId: String.fromEnvironment('macos_appId'),
    messagingSenderId: String.fromEnvironment('macos_messagingSenderId'),
    projectId: String.fromEnvironment('macos_projectId'),
    storageBucket: String.fromEnvironment('macos_storageBucket'),
    iosBundleId: String.fromEnvironment('macos_iosBundleId'),
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('windows_apiKey'),
    appId: String.fromEnvironment('windows_appId'),
    messagingSenderId: String.fromEnvironment('windows_messagingSenderId'),
    projectId: String.fromEnvironment('windows_projectId'),
    authDomain: String.fromEnvironment('windows_authDomain'),
    storageBucket: String.fromEnvironment('windows_storageBucket'),
  );
}
