name: Build and Release APK

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        name: Build Flutter APK
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: 3.24.5

            - name: Install Dependencies
              run: flutter pub get

            - name: Decode Keystore
              env:
                  ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
              run: |
                  echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/release.keystore

            - name: Configure Signing
              env:
                  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
                  ANDROID_KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_KEYSTORE_KEY_ALIAS }}
                  ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
              run: |
                  # Create or modify key.properties file
                  cat > android/key.properties <<EOL
                  storePassword=$ANDROID_KEYSTORE_PASSWORD
                  keyAlias=$ANDROID_KEYSTORE_KEY_ALIAS
                  keyPassword=$ANDROID_KEYSTORE_KEY_PASSWORD
                  storeFile=android/app/release.keystore
                  EOL

            - name: Decode and Set Environment Variables
              env:
                  APP_ENV_BASE64: ${{ secrets.APP_ENV_BASE64 }}
              run: |
                  echo "$APP_ENV_BASE64" | base64 -d > .env
                  echo ".env file created"

            - name: Build Release APK
              env:
                  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
                  ANDROID_KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_KEYSTORE_KEY_ALIAS }}
                  ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
              run: |
                  flutter build apk --dart-define-from-file=.env --build-name=${{ github.ref_name }} --build-number=${{ github.run_number }}

            - name: Upload APK to Release
              uses: softprops/action-gh-release@v1
              with:
                  files: build/app/outputs/flutter-apk/app-release.apk
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
